name: APK and AAB Build

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
  workflow_dispatch:

env:
  BUILD_NUMBER: 1
  BUILD_VERSION: 1.0.0
  PYTHON_VERSION: 3.12.2
  FLUTTER_VERSION: 3.24.1
  APK_PATH: "build/apk/app-release.apk"
  AAB_PATH: "build/aab/app-release.aab"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Build Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential python3-dev

    - name: Clean Build Directory
      run: |
        echo "Cleaning build directory..."
        find . -name "*.pyc" -delete
        rm -rf build

    - name: Setup Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Setup Flutter ${{ env.FLUTTER_VERSION }}
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}

    - name: Setup Java JDK
      uses: actions/setup-java@v4.2.1
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Configure Flutter
      run: |
        flutter config --no-analytics

    - name: Verify Flutter Installation
      run: |
        flutter --version

    - name: Build APK and AAB
      run: |
        echo "Starting APK and AAB build..."
        flet build apk --build-version ${{ env.BUILD_VERSION }} --build-number ${{ env.BUILD_NUMBER }} --verbose > apk_build.log 2>&1
        if [ $? -ne 0 ]; then
          echo "Flet build apk failed. Check apk_build.log for details."
          exit 1
        fi
        flet build aab --build-version ${{ env.BUILD_VERSION }} --build-number ${{ env.BUILD_NUMBER }} --verbose > aab_build.log 2>&1
        if [ $? -ne 0 ]; then
          echo "Flet build aab failed. Check aab_build.log for details."
          exit 1
        fi

    - name: List All Files in Build Directory
      run: |
        echo "Listing all files in the build directory..."
        find build -type f -print || echo "Build directory does not exist or is empty."

    - name: Verify APK and AAB Existence
      id: verify-files
      run: |
        if [ -f "$APK_PATH" ]; then
          echo "APK file found at $APK_PATH"
          echo "APK_PATH=$APK_PATH" >> $GITHUB_ENV
        else
          echo "Error: APK file not found at $APK_PATH!"
          exit 1
        fi
        if [ -f "$AAB_PATH" ]; then
          echo "AAB file found at $AAB_PATH"
          echo "AAB_PATH=$AAB_PATH" >> $GITHUB_ENV
        else
          echo "Error: AAB file not found at $AAB_PATH!"
          exit 1
        fi

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4.3.4
      with:
        name: apk-build-artifact
        path: ${{ env.APK_PATH }}
        if-no-files-found: error
        overwrite: false

    - name: Upload AAB Artifact
      uses: actions/upload-artifact@v4.3.4
      with:
        name: aab-build-artifact
        path: ${{ env.AAB_PATH }}
        if-no-files-found: error
        overwrite: false
